### ISSUE TITLE
Some new features

### ISSUE THREAD

**Issue by bhaskatripathi** [eimenhmdt/autoresearcher#1]
I like your project as I am building a research GPT. Following features will add value:
1. Add a relevance score logic for top 20 citations. Score can be generated based on keyword matching percentage.
2. For a given sentence (which a researcher might know through expert knowledge in the area), Get relevant citations to back the statement. This will be a very useful feature in LR.
3. Shortlist and save papers. Find research gaps in shortlisted papers and summarize them.

Please see if you can implement them. We can also collaborate if you are ready. I am ready to code some of these features.

**Comment by eimenhmdt** [comment]
Hi, thank you for the interesting suggestions. I'll try to figure out how to integrate them into AutoResearcher's roadmap. Will keep you posted!
