### ISSUE TITLE
The same paper is picked up many times

### ISSUE THREAD

**Issue by manuelgug** [eimenhmdt/autoresearcher#20]
In some instances, it seems autoreseracher is reading from the same paper multiple times. Sometimes it goes as far as 5+ times. As expected, this happens more often with more specific questions that may have less literature available in the given time window. 

May be useful to find a way to avoid repeating papers, even if there aren't enough to satisfy the maximum asked for. Just return something like ```no more papers found``` and break or something.

**Comment by sanjaynagi** [comment]
Hi Manuel :)

This should have been addressed by #14 , are you using the latest version of the repo?

**Comment by eimenhmdt** [comment]
Closing the issue, because as @sanjaynagi this has been solved by #14 :)
