### ISSUE TITLE
Error getting DOI citation

### ISSUE THREAD

**Issue by danamlewis** [eimenhmdt/autoresearcher#3]
I kept getting a JSONDecodeError (`raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`) from the function get_citation_by_doi(). 

I currently worked around it by commenting out the function, the extract citation section, and the logic under 'for papers in papers' related to DOI, so the ctiation is just the paper ("url"), but wanted to flag it in case anyone else had a similar issue.

**Comment by eimenhmdt** [comment]
Hey there! Sorry that you had trouble using the project. I'll try to replicate the error. But, it seems odd that the response from the API is not in a valid JSON format. Not sure if it might have something to do with the email environment variable 🤔

I'll keep you posted on any updates. Thanks for bringing this issue to my attention!

**Comment by janzheng** [comment]
Could you please post the print() output of the API response body as text? I can't seem to replicate this error either. Might be their API that's messed up, but it's hard to know for sure.

**Comment by danamlewis** [comment]
I came back to this an hour later, and with the latest version of code, it's now working successfully. So yes, sounds like it likely was an API issue from the citation process. I'll close this issue, since it's working now. Thanks both!

**Comment by eimenhmdt** [comment]
Great to hear that it worked!
