### ISSUE TITLE
Surpassing the max number of tokens allowed

### ISSUE THREAD

**Issue by JulenCestero** [eimenhmdt/autoresearcher#9]
Using this research question: "How to optimize the demand response process using Surrogates trained by Active Learning"

I get the following error running the code in Collab:

> ---------------------------------------------------------------------------
> InvalidRequestError                       Traceback (most recent call last)
> [<ipython-input-6-346fd97931a5>](https://localhost:8080/#) in <cell line: 2>()
>       1 # Run the Literature Review
> ----> 2 researcher = literature_review(research_question, output_file=file)
>       3 researcher()
> 
> 7 frames
> [/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
>     677         stream_error = stream and "error" in resp.data
>     678         if stream_error or not 200 <= rcode < 300:
> --> 679             raise self.handle_error_response(
>     680                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
>     681             )
> 
> InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4255 tokens (2455 in the messages, 1800 in the completion). Please reduce the length of the messages or completion.

I guess this can be easily fixed by bounding the number of tokens in the prompt generated joining the answers (line 48 in autoresearcher/workflows/literature_review/literature_review.py), or updating dynamically the number of tokens requested to OpenAI depending on the number of tokens used in creating the question.

**Comment by eimenhmdt** [comment]
Very good catch, thank you.

Will try to fix this asap and get back to you!

**Comment by eimenhmdt** [comment]
Hey, this issue should be solved with PR #11
